
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [4]:
import numpy as np

array = np.arange(10)  # 0 to 9
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [2]:
array = np.arange(1,10)
array

reshaped_array = array.reshape((3,3))

reshaped_array


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Access the element at the second row, second column.


In [6]:
array_element = reshaped_array [1,1]

array_element

5

Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [7]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [9]:
array = np.array([1,2,3,4,5])

sum1 = np.sum(array)  # array_sum = array.sum()
std1 = np.std(array)  # array_std = array.std()
mean1= np.mean(array)  # array_mean = array.mean()

print("Sum is:", sum1)
print("Standard deviation is:", std1)
print("Mean is:", mean1)

Sum is: 15
Standard deviation is: 1.4142135623730951
Mean is: 3.0


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [10]:
Array = [1,2,3,4,5,6]
Matrix = np.array(Array).reshape (2,3)
print(Matrix)

[[1 2 3]
 [4 5 6]]



# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [15]:
Random_array= np.random.randint(1,100, size = (5,5))
print(Random_array)

[[39 94 49 32 13]
 [34 72 60 78 23]
 [79 33 62 43 73]
 [ 5 38 53 39 46]
 [56 26 11 47 55]]


Replace all values in the sub-array with a specific value.


In [16]:
Random_array[1:4,:] = 10
Random_array

array([[39, 94, 49, 32, 13],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [56, 26, 11, 47, 55]])

Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [23]:
arr = np.array([[1,2], [3,4], [5,6], [7,8]])
arr
arr[[1,3]]

array([[3, 4],
       [7, 8]])


# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [40]:
array = np.array([0,1,2])
array

#title

new_array = np.tile(array, (3,1))

new_array

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [42]:
array_1d = np.array([0,1,2])
array_1d + new_array

array([[0, 2, 4],
       [0, 2, 4],
       [0, 2, 4]])

# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [48]:
Random_array1= np.random.randint(1,100, size = (3,3))
Random_array1

array([[55, 61, 14],
       [63, 86, 40],
       [59, 82, 99]])

In [49]:
Random_array2= np.random.randint(1,100, size = (3,3))
Random_array2

array([[81, 52, 89],
       [42, 34, 70],
       [33, 83, 91]])

In [51]:
#hstack
concatenate_horizontally = np.hstack((Random_array1,Random_array2))
concatenate_horizontally

array([[55, 61, 14, 81, 52, 89],
       [63, 86, 40, 42, 34, 70],
       [59, 82, 99, 33, 83, 91]])

In [52]:
# vstack
concatenate_verticllay = np.vstack((Random_array1,Random_array2))
concatenate_verticllay


array([[55, 61, 14],
       [63, 86, 40],
       [59, 82, 99],
       [81, 52, 89],
       [42, 34, 70],
       [33, 83, 91]])

In [68]:
# hsplit # vsplit

splitted_array = np.hsplit(concatenate_horizontally,2)
random_array1 = splitted_array[0]
random_array2 = splitted_array[1]

print(random_array1,random_array2)

[[55 61 14]
 [63 86 40]
 [59 82 99]] [[81 52 89]
 [42 34 70]
 [33 83 91]]


In [64]:
splitted_array = np.vsplit(concatenate_verticllay,2)
splitted_array  # splitted_array [0]

[array([[55, 61, 14],
        [63, 86, 40],
        [59, 82, 99]]),
 array([[81, 52, 89],
        [42, 34, 70],
        [33, 83, 91]])]

## 

# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop


In [72]:
array = np.array([1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5])

count_dict = {}

for i in array:
    if i in count_dict:
        count_dict[i] += 1
    else:
        count_dict[i] = 1

count_dict

{1: 7, 2: 5, 3: 1, 4: 1, 5: 2, 6: 1, 8: 1, 9: 1, 22: 1, 21: 1}

In [78]:
mode = None
max_count = 0
for key, value in count_dict.items():
    if value > max_count:
        max_count = value
        mode = key

print('Mode:', mode)

Mode: 1


# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

